# Generated by Django 4.2.30 on 2026-05-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_handle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(choices=[('positive', '긍정'), ('negative', '부정'), ('neutral', '중립')], default='neutral', max_length=20)),
                ('like_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('repost_count', models.IntegerField(default=0)),
                ('is_hot', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='stocks.stock')),
            ],
            options={
                'ordering': ['-like_count', '-repost_count', '-posted_at'],
            },
        ),
    ]
