# Generated by Django 4.2.30 on 2026-05-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrendStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_volume', models.BigIntegerField(default=0)),
                ('one_hour_change_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trend_stat', to='stocks.stock')),
            ],
            options={
                'ordering': ['-tweet_volume'],
            },
        ),
    ]
