# Generated by Django 4.2.30 on 2026-05-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stocktrendstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_ko', models.TextField(blank=True, null=True)),
                ('main_sentiment', models.CharField(choices=[('positive', '긍정'), ('negative', '부정'), ('neutral', '중립')], default='neutral', max_length=20)),
                ('positive_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('negative_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('neutral_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('summary_model', models.CharField(default='mT5', max_length=100)),
                ('sentiment_model', models.CharField(default='FinBERT', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='stocks.stock')),
            ],
        ),
    ]
